// <auto-generated />
using EquipmentBookingApp.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EquipmentBookingApp.Domain.Migrations
{
    [DbContext(typeof(EquipmentBookingDbContext))]
    [Migration("20220401005704_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("EquipmentBookingApp.Domain.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "tools",
                            Description = "Secure loose objects with minimal effort. ",
                            Name = "Hammer",
                            Price = 69.989999999999995
                        },
                        new
                        {
                            Id = 2,
                            Category = "tools",
                            Description = "Tighten loose nuts and bolts. ",
                            Name = "Wrench",
                            Price = 49.990000000000002
                        },
                        new
                        {
                            Id = 3,
                            Category = "tools",
                            Description = "Lift any item, no matter how heavy. ",
                            Name = "Pulley",
                            Price = 64.989999999999995
                        },
                        new
                        {
                            Id = 4,
                            Category = "tools",
                            Description = "Tighten any screw professionaly. ",
                            Name = "Pliers",
                            Price = 79.989999999999995
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
